title: Rivaldi Akbar
logo: /assets/img/headshot_circle_low_ratio.png
description: "About Me: As an aspiring Data Analyst, I am enthusiastic about applying my data analysis knowledge and skills to real-world experiences. I have a strong understanding and proficiency in practical data analysis platforms, including Excel, SQL (Big Query), Python, and Tableau. Recently completed a 3 month Full Stack Data Analytics program at RevoU."
show_downloads: false
theme: jekyll-theme-minimal
