title: Rivaldi Akbar
logo: /assets/img/headshot_circle.png
description: About Me: As an aspiring Data Analyst, I am enthusiastic about applying my data analysis knowledge and skills to real-world experiences. I have a strong understanding and proficiency in practical data analysis platforms, including Excel, SQL (Big Query), Python, and Tableau. I am committed to improving my technical skills and apply my newly acquired skills to build a solid foundation for my career. Recently completed a 3 month Full Stack Data Analytics program at RevoU.
#show_downloads: false
theme: jekyll-theme-minimal
