title: Rivaldi Akbar
logo: /assets/img/headshot_circle.png
description: Karawang, Indonesia | rivaldiakbar0403@gmail.com | [LinkedIn](https://www.linkedin.com/in/rivaldi-akbar/)
show_downloads: false
theme: jekyll-theme-minimal
